program TreeListFeaturesDemo;

{$SETPEOSVERSION 5.0}
{$SETPESUBSYSVERSION 5.0}

uses
  MidasLib,
  Forms,
  dxPScxTLLnk,
  cxFilter,
  cxCustomTreeListBaseFormUnit in 'cxCustomTreeListBaseFormUnit.pas' {cxCustomTreeListDemoUnitForm},
  cxUnboundTreeListBaseFormUnit in 'cxUnboundTreeListBaseFormUnit.pas' {cxUnboundTreeListDemoUnitForm},
  cxTreeListPlanetsFormUnit in 'cxTreeListPlanetsFormUnit.pas' {frmPlanets},
  cxTreeListAboutFormUnit in 'cxTreeListAboutFormUnit.pas' {frmAbout},
  cxTreeListExpandableBandsFormUnit in 'cxTreeListExpandableBandsFormUnit.pas' {frmExpandableBands},
  cxTreeListGroupSummaryFormUnit in 'cxTreeListGroupSummaryFormUnit.pas' {frmGroupSummary},
  cxTreeListQuickVisibilityCustomization in 'cxTreeListQuickVisibilityCustomization.pas' {frmQuickVisibilityCustomization},
  cxDBTreeListBaseFormUnit in 'cxDBTreeListBaseFormUnit.pas' {cxDBTreeListDemoUnitForm},
  cxTreeListDataModule in 'cxTreeListDataModule.pas' {dmTreeList: TDataModule},
  cxTreeListDepartmentsFormUnit in 'cxTreeListDepartmentsFormUnit.pas' {frmDepartments},
  cxTreeListBiolifeFormUnit in 'cxTreeListBiolifeFormUnit.pas' {frmBiolife},
  cxTreeListCarsFormUnit in 'cxTreeListCarsFormUnit.pas' {frmCars},
  cxTreeListLevelImagesFormUnit in 'cxTreeListLevelImagesFormUnit.pas' {frmLevelImages},
  cxTreeListNestedBandsFormUnit in 'cxTreeListNestedBandsFormUnit.pas' {frmNestedBands},
  cxTreeListFixedBandsFormUnit in 'cxTreeListFixedBandsFormUnit.pas' {frmFixedBands},
  cxTreeListMultipleSummaryFormUnit in 'cxTreeListMultipleSummaryFormUnit.pas' {frmMultipleSummary},
  cxTreeListSummaryCalculationBaseFormUnit in 'cxTreeListSummaryCalculationBaseFormUnit.pas' {frmSummaryCalculationBase},
  cxTreeListIssueListFormUnit in 'cxTreeListIssueListFormUnit.pas' {frmIssueList},
  cxTreeListImagesFormUnit in 'cxTreeListImagesFormUnit.pas' {frmImages},
  cxTreeListNodeHeightFormUnit in 'cxTreeListNodeHeightFormUnit.pas' {frmNodeHeight},
  cxTreeListNodeVisibilityFormUnit in 'cxTreeListNodeVisibilityFormUnit.pas' {frmNodeVisibility},
  cxTreeListExplorerFormUnit in 'cxTreeListExplorerFormUnit.pas' {frmTreeListExplorer},
  cxTreeListDragAndDropFormUnit in 'cxTreeListDragAndDropFormUnit.pas' {frmDragAndDrop},
  cxVirtualTreeListBaseFormUnit in 'cxVirtualTreeListBaseFormUnit.pas' {cxVirtualTreeListDemoUnitForm},
  cxProviderModeDemoClasses in 'cxProviderModeDemoClasses.pas',
  cxTreeListIniEditorFormUnit in 'cxTreeListIniEditorFormUnit.pas' {frmIniEditor},
  cxColumnsMultiEditorsDemoPopup in 'cxColumnsMultiEditorsDemoPopup.pas' {ColumnsMultiEditorsDemoPopupForm},
  cxTreeListCustomDrawFormUnit in 'cxTreeListCustomDrawFormUnit.pas' {frmCustomDraw},
  cxCustomDrawDemoEditor in 'cxCustomDrawDemoEditor.pas' {CustomDrawDemoEditorForm},
  cxCustomDrawDemoConsts in 'cxCustomDrawDemoConsts.pas',
  cxTreeListCheckGroupsFormUnit in 'cxTreeListCheckGroupsFormUnit.pas' {frmCheckGroups},
  cxTreeListStylesFormUnit in 'cxTreeListStylesFormUnit.pas' {frmTreeListStyles},
  cxTreeListMenusFormUnit in 'cxTreeListMenusFormUnit.pas' {frmMenus},
  cxTreeListPreviewFormUnit in 'cxTreeListPreviewFormUnit.pas' {frmPreview},
  cxTreeListSearchFormUnit in 'cxTreeListSearchFormUnit.pas' {frmSearch},
  cxTreeListFullVirtualFormUnit in 'cxTreeListFullVirtualFormUnit.pas' {frmFullVirtual},
  cxTreeListConditionalFormattingUnit in 'cxTreeListConditionalFormattingUnit.pas' {frmConditionalFormatting},
  cxTreeListFilterControlFormUnit in 'cxTreeListFilterControlFormUnit.pas' {frmFilterControl},
  cxTreeListFilterPopupFormUnit in 'cxTreeListFilterPopupFormUnit.pas' {frmFilterPopup},
  cxTreeListFindPanelFormUnit in 'cxTreeListFindPanelFormUnit.pas' {frmFindPanel},
  cxTreeListFeaturesDemoUtils in 'cxTreeListFeaturesDemoUtils.pas',
  cxTreeListFeaturesDemoStrConsts in 'cxTreeListFeaturesDemoStrConsts.pas',
  dxAboutDemo in '..\Common\dxAboutDemo.pas' {dxAboutDemoForm},
  dxDemoBaseMainForm in '..\Common\dxDemoBaseMainForm.pas' {frmMainBase},
  dxDemoObjectInspector in '..\Common\dxDemoObjectInspector.pas' {frmInspector},
  dxDemoPrintFrame in '..\Common\dxDemoPrintFrame.pas' {frmPrinting: TFrame},
  dxExportProgressDialog in '..\Common\dxExportProgressDialog.pas',
  Main in 'Main.pas' {frmMain},
  cxTreeListExcelStyleFiltering in 'cxTreeListExcelStyleFiltering.pas' {frmExcelStyleFiltering},
  cxTreeListCalculatedFields in 'cxTreeListCalculatedFields.pas' {frmCalculatedFields},
  dxAutoGenerateData in '..\Common\dxAutoGenerateData.pas' {dmAutoGenerateData: TDataModule},
  cxTreeListScrollbarAnnotations in 'cxTreeListScrollbarAnnotations.pas' {frmScrollbarAnnotations},
  dxScrollbarAnnotationControlPanel in 'dxScrollbarAnnotationControlPanel.pas' {frScrollbarAnnotationControlPanel: TFrame},
  cxTreeListFilterExpressionFormUnit in 'cxTreeListFilterExpressionFormUnit.pas' {frmFilterExpression},
  dxDemoUtils in '..\Common\dxDemoUtils.pas';

{$R *.res}
{$R ..\Common\dxDPIAwareManifestPM2.res}

begin
  cxFilter.dxFilterCriteriaDisplayStyle := fcdsTokens;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'ExpressQuantumTreeList Features Demo';
  Application.CreateForm(TdmTreeList, dmTreeList);
  Application.CreateForm(TdmAutoGenerateData, dmAutoGenerateData);
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
