program GridFeaturesDemo;

{$SETPEOSVERSION 5.0}
{$SETPESUBSYSVERSION 5.0}

{$R *.dres}

uses
  Forms,
  Dialogs,
  jpeg,
  cxFilter,
  dxCustomDemoFrameUnit in 'dxCustomDemoFrameUnit.pas' {dxCustomDemoFrame: TFrame},
  dxFrames in 'dxFrames.pas',
  maindata in 'maindata.pas' {dmMain: TDataModule},
  dxDBFrame in 'dxDBFrame.pas' {dxDBFrame: TFrame},
  dxGridFrame in 'dxGridFrame.pas' {dxGridFrame: TFrame},
  uGridViews in 'uGridViews.pas' {frmViewsGrid: TFrame},
  uGridMasterDetail in 'uGridMasterDetail.pas' {frmGridMasterDetail: TFrame},
  uGridConditionalFormatting in 'uGridConditionalFormatting.pas' {frmGridConditionalFormatting: TFrame},
  uGridCardView in 'uGridCardView.pas' {frmCardViewGrid: TFrame},
  uGridBandedView in 'uGridBandedView.pas' {frmGridBandedView: TFrame},
  uGridLayoutView in 'uGridLayoutView.pas' {frmGridLayoutView: TFrame},
  uGridUnbound in 'uGridUnbound.pas' {frmGridUnbound: TFrame},
  uGridCustomSummaries in 'uGridCustomSummaries.pas' {frmCustomGridSummaries: TFrame},
  uGridFiltering in 'uGridFiltering.pas' {frmFitleringGrid: TFrame},
  uGridSummaries in 'uGridSummaries.pas' {frmGridSummaries: TFrame},
  uGridPreview in 'uGridPreview.pas' {frmGridPreview: TFrame},
  uGridRowAutoHeight in 'uGridRowAutoHeight.pas' {frmGridAutoHeight: TFrame},
  uGridFixedBands in 'uGridFixedBands.pas' {frmGridFixedBands: TFrame},
  uGridIncSearch in 'uGridIncSearch.pas' {frmIncSearchGrid: TFrame},
  uGridNewItemRow in 'uGridNewItemRow.pas' {frmNewItemRowGrid: TFrame},
  uGridMultipleEditors in 'uGridMultipleEditors.pas' {frmMultiEditorsGrid: TFrame},
  uGridAdvancedFiltering in 'uGridAdvancedFiltering.pas' {frmAdvancedFilteringGrid: TFrame},
  uGridDragDrop in 'uGridDragDrop.pas' {frmDragDropGrid: TFrame},
  uGridInplaceEditors in 'uGridInplaceEditors.pas' {frmInplaceEditorsGrid: TFrame},
  uStrsConst in 'uStrsConst.pas',
  uGridBuildInNavigator in 'uGridBuildInNavigator.pas' {frmGridBuildInNavigator: TFrame},
  uGridCellSelection in 'uGridCellSelection.pas' {frmGridCellSelection: TFrame},
  uGridMergeCells in 'uGridMergeCells.pas' {frmGridMergeCells: TFrame},
  uGridUnboundColumns in 'uGridUnboundColumns.pas' {frmGridUnboundColumns: TFrame},
  uGridNestedBands in 'uGridNestedBands.pas' {frmGridNestedBands: TFrame},
  uGridOffice11 in 'uGridOffice11.pas' {frmGridOffice11: TFrame},
  FrameIDs in 'FrameIDs.pas',
  cxGridDemoUtils in 'cxGridDemoUtils.pas',
  dxDemoUtils in '..\Common\dxDemoUtils.pas',
  uGridChartView in 'uGridChartView.pas' {dxGridChartViewFrame: TFrame},
  uGridServerMode in 'uGridServerMode.pas' {dxGridServerMode: TFrame},
  uGridServerModeQuery in 'uGridServerModeQuery.pas' {dxGridServerModeQuery: TFrame},
  dxAboutDemo in '..\Common\dxAboutDemo.pas' {dxAboutDemoForm},
  dxDemoBaseMainForm in '..\Common\dxDemoBaseMainForm.pas' {frmMainBase},
  dxExportProgressDialog in '..\Common\dxExportProgressDialog.pas',
  dxSplashUnit in '..\Common\dxSplashUnit.pas' {TfrmSplash},
  Main in 'Main.pas' {frmMain},
  dxDemoObjectInspector in '..\Common\dxDemoObjectInspector.pas' {frmInspector},
  PropertiesPopup in '..\Common\PropertiesPopup.pas' {fmPopupTree},
  uGridLayoutViewCarouselMode in 'uGridLayoutViewCarouselMode.pas' {frmGridLayoutViewCarouselMode},
  uGridInplaceEditForm in 'uGridInplaceEditForm.pas' {frmGridInplaceEditForm},
  uGridFindPanel in 'uGridFindPanel.pas' {frmGridFindPanel: TFrame},
  uGridFixedGroups in 'uGridFixedGroups.pas',
  uGridSparkLines in 'uGridSparkLines.pas' {frmGridSparklines},
  uGridWinExplorerView in 'uGridWinExplorerView.pas' {frmGridWinExplorerView: TFrame},
  uGridCalloutPopup in 'uGridCalloutPopup.pas' {frmGridCalloutPopup: TFrame},
  uGridLayoutViewGroupScrolling in 'uGridLayoutViewGroupScrolling.pas' {frmGridLayoutViewGroupScrolling: TFrame},
  uGridMergedGroups in 'uGridMergedGroups.pas' {frmGridMergedGroups},
  uGridCheckBoxMultiSelect in 'uGridCheckBoxMultiSelect.pas' {frmGridCheckBoxMultiSelect},
  uGridFilterRow in 'uGridFilterRow.pas' {frmGridFilterRow: TFrame},
  uGridFixedDataRows in 'uGridFixedDataRows.pas' {frmGridFixedDataRows: TFrame},
  dxDemoPrintFrame in '..\Common\dxDemoPrintFrame.pas' {frmPrinting: TFrame},
  uGridExcelStyleFiltering in 'uGridExcelStyleFiltering.pas' {frmGridExcelStyleFiltering: TFrame},
  uGridCalculatedFields in 'uGridCalculatedFields.pas' {frmGridCalculatedFields: TFrame},
  uGridScrollbarAnnotations in 'uGridScrollbarAnnotations.pas' {frmGridScrollbarAnnotations: TFrame},
  dxScrollbarAnnotationControlPanel in 'dxScrollbarAnnotationControlPanel.pas' {frScrollbarAnnotationControlPanel: TFrame},
  dxAutoGenerateData in '..\Common\dxAutoGenerateData.pas' {dmAutoGenerateData: TDataModule},
  uGridFilterExpression in 'uGridFilterExpression.pas' {frmGridFilterExpression: TFrame},
  uGridCustomRowLayout in 'uGridCustomRowLayout.pas' {frmGridCustomRowLayout: TFrame},
  uGridOfficeCompactView in 'uGridOfficeCompactView.pas' {frmGridOfficeCompactView: TFrame},
  uGridTableViewHotTrack in 'uGridTableViewHotTrack.pas' {frmTableViewHotTrack: TFrame},
  uGridFixedColumns in 'uGridFixedColumns.pas' {frmGridFixedColumns: TFrame};

{$R *.res}
{$R ..\Common\dxDPIAwareManifestPM2.res}

begin
  cxFilter.dxFilterCriteriaDisplayStyle := fcdsTokens;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TdmMain, dmMain);
  Application.CreateForm(TdmAutoGenerateData, dmAutoGenerateData);
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
