{*******************************************}
{                                           }
{           FastQueryBuilder v1.03          }
{               Include file                }
{                                           }
{          Copyright (c) 2004-2015          }
{              Fast Reports Inc.            }
{                                           }
{*******************************************}
{$I frVer.inc}

{$J+} {- Writeable structured consts }
{$WARNINGS OFF}
