program VerticalGridFeaturesDemo;

{$SETPEOSVERSION 5.0}
{$SETPESUBSYSVERSION 5.0}

uses
  Forms,
  Dialogs,
  cxFilter,
  uStrsConst in 'uStrsConst.pas',
  dxCustomDemoFrameUnit in 'dxCustomDemoFrameUnit.pas' {dxCustomDemoFrame: TFrame},
  dxFrames in 'dxFrames.pas',
  FrameIDs in 'FrameIDs.pas',
  maindata in 'maindata.pas' {dmMain: TDataModule},
  Propertiespopup in '..\Common\Propertiespopup.pas' {fmPopupTree},
  dxVertGridFrame in 'dxVertGridFrame.pas' {VerticalGridFrame: TFrame},
  uVertGridCustomMultiRecords in 'uVertGridCustomMultiRecords.pas' {frmCustomVertGridMultiRecords: TFrame},
  uVertGridMultiRecords in 'uVertGridMultiRecords.pas' {frmVertGridMultiRecords: TFrame},
  uVertGridFindPanel in 'uVertGridFindPanel.pas' {frmVerticalGridFindPanel: TFrame},
  uVertGridFilterPopup in 'uVertGridFilterPopup.pas' {frmVerticalGridFilterPopup: TFrame},
  uConditionalFormatting in 'uConditionalFormatting.pas' {frmConditionalFormatting: TFrame},
  uVertGridStyles in 'uVertGridStyles.pas' {frmVertGridStyles: TFrame},
  uVertGridIncSearch in 'uVertGridIncSearch.pas' {frmVerticalGridIncSearch: TFrame},
  uVertGridFilterControl in 'uVertGridFilterControl.pas' {frmVerticalGridFilterControl: TFrame},
  uVertGridNavigator in 'uVertGridNavigator.pas' {frmVertGridNavigator: TFrame},
  uVertGridInplaceEditors in 'uVertGridInplaceEditors.pas' {frmVertGridInplaceEditors: TFrame},
  uVertGridInplaceEditorsValidation in 'uVertGridInplaceEditorsValidation.pas' {frmVertGridInplaceEditorsValidation: TFrame},
  uVertGridCustomDraw in 'uVertGridCustomDraw.pas' {frmVertGridCustomDraw: TFrame},
  uVertGridRTTI in 'uVertGridRTTI.pas' {frmVerticalGridRTTI: TFrame},
  uVertGridBitmap in 'uVertGridBitmap.pas' {frmVertGridBitmap: TFrame},
  cxVerticalGridDemoUtils in 'cxVerticalGridDemoUtils.pas',
  dxAboutDemo in '..\Common\dxAboutDemo.pas' {dxAboutDemoForm},
  dxDemoBaseMainForm in '..\Common\dxDemoBaseMainForm.pas' {frmMainBase},
  dxExportProgressDialog in '..\Common\dxExportProgressDialog.pas',
  dxDemoObjectInspector in '..\Common\dxDemoObjectInspector.pas' {frmInspector},
  dxDemoPrintFrame in '..\Common\dxDemoPrintFrame.pas' {frmPrinting: TFrame},
  Main in 'Main.pas' {frmMain},
  uVertGridExcelStyleFiltering in 'uVertGridExcelStyleFiltering.pas' {frmExcelStyleFiltering: TFrame},
  uVertGridCalculatedFields in 'uVertGridCalculatedFields.pas' {frmCalculatedFields: TFrame},
  uVertGridScrollAnnotations in 'uVertGridScrollAnnotations.pas' {frmScrollAnnotations: TFrame},
  dxAutoGenerateData in '..\Common\dxAutoGenerateData.pas' {dmAutoGenerateData: TDataModule},
  dxScrollbarAnnotationControlPanel in 'dxScrollbarAnnotationControlPanel.pas' {frScrollbarAnnotationControlPanel: TFrame},
  uVertGridFilterExpression in 'uVertGridFilterExpression.pas' {frmFilterExpression: TFrame},
  dxDemoUtils in '..\Common\dxDemoUtils.pas';

{$R *.res}
{$R ..\Common\dxDPIAwareManifestPM2.res}

begin
  cxFilter.dxFilterCriteriaDisplayStyle := fcdsTokens;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'ExpressVerticalGrid Features Demo';
  if HasJet then
  begin
    Application.CreateForm(TdmMain, dmMain);
  Application.CreateForm(TdmAutoGenerateData, dmAutoGenerateData);
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
  end
  else
    ShowMessage(ThereisNoMDACMessage);
end.
